### ISSUE TITLE
wafel_core relies on glslc when it really shouldn't

### ISSUE THREAD

**Issue by notgull** [branpk/wafel#21]
From the [downloads page](https://github.com/google/shaderc#downloads) for glslc:

> **Note: These binaries are just the artifacts of the builders and have not undergone any QA, thus they should be considered unsupported.**

At the present time, the `wafel_core` create seems to rely on `glslc` as a way of pre-compiling the GL shaders, Relying on an unsupported binary is a surefire way to ensure your software isn't future-proof, and (IIRC) pre-compiling shaders isn't portable between GPUs.

**Comment by notgull** [comment]
Did some research. Apparently, the proper way of doing this is to use [`glslang`](https://github.com/KhronosGroup/glslang)?

**Comment by branpk** [comment]
I agree that the dependency on glslc is not ideal. I think we'll switch to [naga](https://github.com/gfx-rs/naga) once it's more stable, since we're using wgpu.

> and (IIRC) pre-compiling shaders isn't portable between GPUs.

Do you have any more info on this? I would have guessed that SPIR-V would be more portable than GLSL, not less.

**Comment by branpk** [comment]
I updated master to use naga, so there's no longer a dependency on glslc.
