### ISSUE TITLE
Release libsm64's source code

### ISSUE THREAD

**Issue by jgcodes2020** [branpk/wafel#22]
Not sure if you would be OK with it, but this would make diagnosing issues with libsm64-based bruteforcing code super easy.

I'm also working on a commons library to interface with said dll in bruteforcers.

**Comment by branpk** [comment]
Source code is currently [here](https://github.com/branpk/sm64_source/tree/libsm64). It's not public, but ask around in the discord for how to get access to sm64_source.

I wouldn't be willing to make this code public, but I'd be open to creating a branch for it on the main sm64_source repo. That's probably a good idea to make it easier for others to maintain / keep up to date with upstream.

**Comment by simonlindholm** [comment]
> I wouldn't be willing to make this code public, but I'd be open to creating a branch for it on the main sm64_source repo. That's probably a good idea to make it easier for others to maintain / keep up to date with upstream.

+1! There's also a fair number of people with access to the main repo but not to forks.

**Comment by jgcodes2020** [comment]
@branpk I think that having an upstream branch at sm64_source is a good idea.

**Comment by branpk** [comment]
Ah I didn't realize that forks had more limited access than the main repo.

I created it [here](https://github.com/SM64-TAS-ABC/sm64_source/tree/libsm64). It's pretty out of date from pc-port but I don't have time to update it at the moment, so feel free to do so.
