### ISSUE TITLE
libsm64: Use GCC debug switches "-gdwarf-4 -g3 -gpubnames"

### ISSUE THREAD

**Issue by jgcodes2020** [branpk/wafel#24]
These switches specify to use DWARF 4, enable macro debug info (likely helpful when accessing object fields), and enable better global symbol lookup. Shouldn't affect Wafel as an application, but will likely ease adding object field support to libwafel.

**Comment by jgcodes2020** [comment]
These options are also helpful for Pancake, since the library I'm using is pretty low-level (I can do things like read raw DIEs, traverse the DIE tree).

I suppose I can submit this as a PR to the private repo.

**Comment by branpk** [comment]
Adding `-gdwarf-4` and `-gpubnames` makes sense to me. But `-g3` seems to increase the library size 4x, so I'd like to avoid it if possible.

I use this build step for macros:

```
$(BUILD_DIR)/macros.txt: $(C_FILES)
    $(V)$(CC) -E -dM $(CFLAGS) -o $@ $&lt;
```

Then I parse those into constants & object fields, which are available in json [here](https://github.com/branpk/wafel/blob/main/wafel_layout/sm64_macro_defns.json).

Does one of those work for you?

**Comment by jgcodes2020** [comment]
I can work with the macro JSON, but adding `-gdwarf-4 -gpubnames` switches is still going to be needed.

**Comment by branpk** [comment]
The libsm64 in Wafel master now uses `-gdwarf-4 -gpubnames -fno-eliminate-unused-debug-types`. (I also updated to the latest libsm64, so might be buggy.) I'll update the libsm64 branch when I get the chance.
